export const CartActionsTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEMS: "ADD_ITEMS",
  ADD_CARTS_ITEMS_FROM_FIREBASE: "ADD_CARTS_ITEMS_FROM_FIREBASE",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_CART_ON_STATE: "CLEAR_CART_ON_STATE",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  UPDATE_CARTS_ITEMS_ON_FIREBASE: "UPDATE_CARTS_ITEMS_ON_FIREBASE",
  CLEAR_CART_ON_FIREBASE_AND_STATE: "CLEAR_CART_ON_FIREBASE_AND_STATE",
};
