export const PaymentActionTypes = {
    SET_SHIPPING_DATA: "SET_SHIPPING_DATA",
    SET_BILLING_DATA: "SET_BILLING_DATA",
    SET_ACTIVE_FORM: "SET_ACTIVE_FORM",
    SET_PAYMENT_DONE: "SET_PAYMENT_DONE"
}